---
version: '3'
services:
  threejs-radar:
    image: "blastbeng/threejs-radar:1.0.0"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    pull_policy: build
    build:
      context: .
      dockerfile: "./Dockerfile"
    ports:
      - 3002:3002
    restart: "unless-stopped"
    container_name: threejs-radar